### ISSUE TITLE
Show errors in browser

### ISSUE THREAD

**Issue by planttheidea** [zhirzh/flow-babel-webpack-plugin#1]
Forgive me for not investigating this myself (on the train when I discovered this), but do the errors propagate to the browser console the way things like ESLint errors do?

**Comment by zhirzh** [comment]
I have tested [`webpack-dev-server`](https://github.com/webpack/webpack-dev-server) and it works just fine.

![test](https://cloud.githubusercontent.com/assets/8132723/19188743/72477b86-8cb1-11e6-88d7-5c64ea22d105.png)

I hope this is what you were asking for.

**Comment by planttheidea** [comment]
This does look on target with what I hoped for. I'll confirm myself once i get in and close assuming the same result. Thanks for jumping on this so quickly!

**Comment by planttheidea** [comment]
Confirmed! Solid stuff man, been looking for this exact thing for a long time. Cheers.
