### ISSUE TITLE
What license is this code under?

### ISSUE THREAD

**Issue by mrc** [zhirzh/flow-babel-webpack-plugin#13]
Hi Shirsh! What's the license for this repo?

**Comment by zhirzh** [comment]
Guthub's default ISC licence. It is [mentioned in `package.json`](https://github.com/zhirzh/flow-babel-webpack-plugin/blob/d825fffa70f8080000ca62a166de00577a04e8a8/package.json#L26)

**Comment by mrc** [comment]
Thanks!

**Comment by zhirzh** [comment]
I wonder why you needed to ask. Care to elaborate?

**Comment by mrc** [comment]
I was just curious. Thanks for replying so quickly!
