### ISSUE TITLE
NPM doesn't have latest fix

### ISSUE THREAD

**Issue by liamcardenas** [zhirzh/flow-babel-webpack-plugin#14]
The latest commit (68eb459da232e01f829d14399a27d9a8134b2e84) is not included in the npm package so the error prints twice.

Thanks for this plugin, btw!

**Comment by ghost** [comment]
workaround: `npm install --save-dev https://github.com/zhirzh/flow-babel-webpack-plugin/tarball/master`

**Comment by zhirzh** [comment]
Looks like I force pushed at some point. My bad.
Fixed in be6da533d93e0e1174ffad615b3e36fd46e13158
